### ISSUE TITLE
[FEATURE] Update the build system to gradle

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-oci-object-storage#15] opened 2022-09-14 19:58 UTC
### Is your feature request related to a problem?
OpenSearch recommends using gradle build system as it already exposes a lot of tools which can be used. 

### What is your proposal
Update the build system to gradle.

**Comment by samuel-oci** [comment] 2023-02-21 23:01
Closing as this seems like a duplicate of https://github.com/opensearch-project/opensearch-oci-object-storage/issues/20

**Closed by samuel-oci** 2023-02-21 23:01 UTC
Labels: enhancement
